In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import WhiteKernel, RBF
from modAL.models import ActiveLearner

%matplotlib inline

In [2]:
X = np.random.uniform(low=1, high=10, size=(200, 4))
y = np.sum(np.sin(X) + np.random.normal(scale=0.1, size=X.shape), axis=-1)

In [3]:
# np.sum(np.sin(X), axis=-1).shape

In [5]:
def GP_regression_std(regressor, X, batch_size):
    _, std = regressor.predict(X, return_std=True)
    print(len(std))
    query_idx = np.argmax(std)
    dist=np.exp(std)
    dist/=np.sum(dist)
    query_idics=np.random.choice(range(len(dist)), batch_size, p=dist)
    return query_idics#, X[query_idx]

In [14]:
n_initial = 128
initial_idx = np.random.choice(range(X.shape[0]), size=n_initial, replace=True)
X_training, y_training = X[initial_idx], y[initial_idx]
kernel = RBF(length_scale=1.0, length_scale_bounds=(1e-2, 1e3)) + WhiteKernel(noise_level=1, noise_level_bounds=(1e-10, 1e+1))

print(X_training.shape, y_training.shape)
regressor = ActiveLearner(
    estimator=GaussianProcessRegressor(kernel=kernel),
    query_strategy=GP_regression_std,
    X_training=X_training, y_training=y_training
)


(128, 4) (128,)


/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-10. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(


In [7]:

X_grid = np.linspace((1,1,1,1), (10,10,10,10), 4000)
y_pred, y_std = regressor.predict(X_grid, return_std=True)
y_pred, y_std = y_pred.ravel(), y_std.ravel()

In [9]:
len(y_std)

4000

In [15]:
n_queries = 10
batch_size=11
for idx in range(n_queries):
    query_idics,_ = regressor.query(X, batch_size)
    print(query_idics, X[query_idics].shape, y[query_idics].shape)
    regressor.teach(X[query_idics].reshape(batch_size, -1), y[query_idics])

200
[  1 180  56 138  76 174   5  44 184 170 181] (11, 4) (11,)
200
[146 128 152  63 184  97 111  83  41 100  21] (11, 4) (11,)


/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/_gpr.py:629: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)
/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-10. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-10. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/home/ji

200
[ 42 184 152 160 160  28   3  94 181 143   2] (11, 4) (11,)
200
[ 27  74  78 100 118 179 171  10 154  83 159] (11, 4) (11,)
200
[110 129 162 129  80 139 153 154  84  19 127] (11, 4) (11,)


/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/_gpr.py:629: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)
/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-10. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-10. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/home/ji

200
[ 68 173  46  99 148  98  37 189  29 158 100] (11, 4) (11,)
200
[138 113  37 106  55 119  38 108 106  67  19] (11, 4) (11,)
200
[160  52 176  15 103  53  68  92 101  53 103] (11, 4) (11,)


/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/_gpr.py:629: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)
/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-10. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-10. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(


200
[133 185 131  86 154 126   6  16  53  31 198] (11, 4) (11,)
200
[ 83 146 112  80 144 173  89  95  66  75  43] (11, 4) (11,)


/home/jiangnan/miniconda3/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-10. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(


In [17]:
y_pred_final, y_std_final = regressor.predict(X_grid, return_std=True)
y_pred_final, y_std_final = y_pred_final.ravel(), y_std_final.ravel()

In [ ]:

with plt.style.context('seaborn-white'):
    plt.figure(figsize=(10, 8))
    plt.plot(X_grid, y_pred_final, linewidth=1.5, color='red')
    plt.fill_between(X_grid, y_pred_final - y_std_final, y_pred_final + y_std_final, alpha=0.2)
    plt.scatter(X, y, c='k', s=20, alpha=0.2)
    plt.title('Prediction after active learning')
    plt.show()

In [18]:
y_std_final

array([0.77603201, 0.77481169, 0.77358725, ..., 0.95523855, 0.95557501,
       0.95590952])